/**
 * Compose each probe into a SELF-CONTAINED file.
 *
 * The probe runner evaluates a single function expression and cannot resolve
 * imports, so a probe cannot `import` the shared driving helpers at run time.
 * Rather than copy those helpers into every probe (and let them drift), each
 * probe is written against them and this script inlines them, producing
 * `build/<name>.mjs` — one arrow function, no imports, ready to run.
 *
 *   node scripts/observe/compose.mjs
 */
import fs from 'fs';
import path from 'path';
import {fileURLToPath} from 'url';

const here = path.dirname(fileURLToPath(import.meta.url));
const outDir = path.join(here, 'build');
fs.mkdirSync(outDir, {recursive: true});

const lib = fs.readFileSync(path.join(here, 'lib-drive.mjs'), 'utf8')
	.replace(/^export /gm, '');

const probes = fs.readdirSync(here)
	.filter(f => f.endsWith('.mjs') && !['lib-drive.mjs', 'compose.mjs'].includes(f));

for (const file of probes) {
	const source = fs.readFileSync(path.join(here, file), 'utf8');
	const body = source
		.replace(/^import[^;]+;$/gm, '')
		.replace(/export default async \(page(?:, options = \{\})?\)\s*=>\s*\{/, 'const __run = async (page, options = {}) => {');

	const composed = `// GENERATED by scripts/observe/compose.mjs from ${file} — do not edit.\n`
		+ `async (page) => {\n${lib}\n${body}\nreturn await __run(page, {});\n}\n`;

	fs.writeFileSync(path.join(outDir, file), composed);
	console.log(`composed build/${file}`);
}
